#include "GHIElectronics_TinyCLR_Devices_Dac.h"

static const TinyCLR_Interop_MethodHandler methods[] = {
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    Interop_GHIElectronics_TinyCLR_Devices_Dac_GHIElectronics_TinyCLR_Devices_Dac_Provider_DacControllerApiWrapper::get_ChannelCount___I4,
    Interop_GHIElectronics_TinyCLR_Devices_Dac_GHIElectronics_TinyCLR_Devices_Dac_Provider_DacControllerApiWrapper::get_ResolutionInBits___I4,
    Interop_GHIElectronics_TinyCLR_Devices_Dac_GHIElectronics_TinyCLR_Devices_Dac_Provider_DacControllerApiWrapper::get_MinValue___I4,
    Interop_GHIElectronics_TinyCLR_Devices_Dac_GHIElectronics_TinyCLR_Devices_Dac_Provider_DacControllerApiWrapper::get_MaxValue___I4,
    Interop_GHIElectronics_TinyCLR_Devices_Dac_GHIElectronics_TinyCLR_Devices_Dac_Provider_DacControllerApiWrapper::OpenChannel___VOID__I4,
    Interop_GHIElectronics_TinyCLR_Devices_Dac_GHIElectronics_TinyCLR_Devices_Dac_Provider_DacControllerApiWrapper::CloseChannel___VOID__I4,
    Interop_GHIElectronics_TinyCLR_Devices_Dac_GHIElectronics_TinyCLR_Devices_Dac_Provider_DacControllerApiWrapper::Write___VOID__I4__I4,
    nullptr,
    nullptr,
    Interop_GHIElectronics_TinyCLR_Devices_Dac_GHIElectronics_TinyCLR_Devices_Dac_Provider_DacControllerApiWrapper::Acquire___VOID,
    Interop_GHIElectronics_TinyCLR_Devices_Dac_GHIElectronics_TinyCLR_Devices_Dac_Provider_DacControllerApiWrapper::Release___VOID,
};

const TinyCLR_Interop_Assembly Interop_GHIElectronics_TinyCLR_Devices_Dac = {
    "GHIElectronics.TinyCLR.Devices.Dac",
    0x78B11928,
    methods
};
